services:
  pyde1:
    build:
      context: .
      args:
        - BROKER_HOSTNAME=localhost
#    ports:
#      - 1234:1234
    depends_on:
      - broker
#    networks:
#      - mosquitto
#      - host
    volumes:
      - ./db/:/var/lib/pyde1
      - ./log/:/var/log/pyde1
    # for bluetooth pass-through
    #privileged: true
    cap_add:
      - NET_ADMIN
    network_mode: host

  broker:
    image: eclipse-mosquitto:2.0.15
#    ports:
#      - 1883:1883
#    networks:
#      - mosquitto
    network_mode: host
    command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]

#  test:
#    build:
#      dockerfile: test.Dockerfile
#      context: ./

networks:
    mosquitto:
        name: mosquitto
        driver: bridge

